  02:57:44.408  TimerHandler: ready  -  Server - TimerHandler:88
  02:57:44.410  CoinHandler: ready  -  Server - CoinHandler:137
  02:57:44.410  LoadCharacterHandler: ready  -  Server - LoadCharacterHandler:29
  02:57:44.426  Requiring asset 3239236979.
Callstack:
Workspace.HD Admin.Core.MainModule, line 1
  -  Server - MainModule:1
  02:57:45.975  JointsService is deprecated, but an instance was added to JointsService: JointsService.Weld   -  Studio
  02:57:45.982  Workspace.Devel.A-Chassis Tune.Initialize:318: invalid argument #1 to 'abs' (number expected, got nil)  -  Server - Initialize:318
  02:57:45.983  Stack Begin  -  Studio
  02:57:45.983  Script 'Workspace.Devel.A-Chassis Tune.Initialize', Line 318  -  Studio - Initialize:318
  02:57:45.983  Stack End  -  Studio
  02:57:46.026  value of type nil cannot be converted to a number  -  Server - Initialize:296
  02:57:46.026  Stack Begin  -  Studio
  02:57:46.026  Script 'Workspace.Tesla Cybertruck.A-Chassis Tune.Initialize', Line 296  -  Studio - Initialize:296
  02:57:46.026  Stack End  -  Studio
  02:57:46.029  value of type nil cannot be converted to a number  -  Server - Initialize:296
  02:57:46.029  Stack Begin  -  Studio
  02:57:46.029  Script 'Workspace.Tesla Cybertruck.A-Chassis Tune.Initialize', Line 296  -  Studio - Initialize:296
  02:57:46.029  Stack End  -  Studio
  02:57:48.665  JointsService is deprecated, but an instance was added to JointsService: JointsService.Weld   -  Studio
  02:57:49.675  CheckpointHandler: map folder not found in Workspace: SkyscraperMap  -  Server - CheckpointHandler:65
  02:57:49.675  CheckpointHandler: map folder not found in Workspace: BigFootMap  -  Server - CheckpointHandler:65
  02:57:49.676  CheckpointHandler: map folder not found in Workspace: HighSpeedMap  -  Server - CheckpointHandler:65
  02:57:49.676  CheckpointHandler: ready — monitoring 3 map(s)  -  Server - CheckpointHandler:213
  02:57:50.384  MainMenu: Skipping menu - HasPlayed: nil, HasCharacter: true  -  Client - MainMenu:23